spring:
  application:
    name: immobilien-management

logging:
  level:
    '[com.sartorius.ismart.demo]': TRACE
    root: INFO

remoteService:
  serviceProvider:
    groupId: com.dynsers.dynservice
    resourceId: register
    resourceVersion: 0.0.1
    context-path: remoteservice

  server:
    groupId: com.dynsers.dynservice
    resourceId: register
    resourceVersion: 0.0.1
    serviceVersion: 0.0.1
    url: http://localhost:9081/remoteservice/

server:
  port: 9080
