---
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    ismart2:
      url: jdbc:postgresql://localhost:5435/ismart2
      username: ismartregister
      password: ENC(CM091eDtmEnZ3y2cC65G6KtXTH5hFldCqegwfWJYAfKX3i4fp/2ccGjqK+WNQc5s)
    liquibase:
      url: jdbc:postgresql://localhost:5435/ismart2
      username: postgres
      password: ENC(mVOy2SJD5eQA+tOF8+0y+k3tjGs9ZMWBVFu/hRu9m1FepEOpvFJFrr9HyY9/ghIu)
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog-with-mockdata.xml

server:
  port: 9080

management:
  server:
    port: 8082

remoteService:
  serviceProvider:
    groupId: com.sartorius.ismart2
    protocol: http
    resourceId: register
    resourceVersion: 0.0.1
    serviceLocation: central
    context-path: ismart2
