spring:
  application:
    name: remoteservice-server
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:5432/dynserviceregister
    username: register
    password: register
    driverClassName: org.postgresql.Driver

logging:
  level:
    com.dynsers.remoteservice: DEBUG
    root: INFO

remoteService:
  serviceProvider:
    groupId: com.dynsers.dynservice
    resourceId: register
    resourceVersion: 0.0.1
    context-path: remoteservice


server:
  port: 9081
